name: http_client
description: |
    A platform-independent HTTP client API supporting browser, console, and curl (for SOCKS proxy).
version: 0.4.4+1
author: Istvan Soos <istvan.soos@gmail.com>

homepage: https://github.com/isoos/http_client

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  executor: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: ^0.12.42
